version: '3.5'

services:
 
  firefly.mssql:
    build:
      context: ./docker-setup/mssql/
      dockerfile: Dockerfile      
    container_name: firefly.mssql
    ports:
      - 1422:1433
    environment:
      SA_PASSWORD: gso2h8gh4ww8agwe224*d
      ACCEPT_EULA: Y
